### ISSUE TITLE
Нерабочая ссылка на checkstyle.xml

### ISSUE THREAD

**Issue by mkovarsky** [netology-code/javaqa-homeworks#3]
## Шаги для воспроизведения
1. Открываем [Домашнее задание к занятию «Выстраивание процесса непрерывной интеграции (CI): Github Actions. Покрытие кода с JaCoCo, статический анализ кода: CheckStyle, SpotBugs»](https://github.com/netology-code/javaqa-homeworks/tree/master/ci)
2. Переходим к блоку Задача №3 (необязательная) - "Внедряем стандарты кодирования"
3. Нажимаем на  checkstyle.xml
![image](https://user-images.githubusercontent.com/60435481/76416521-4d434380-63ac-11ea-8509-0fbe5a1aaa0c.png)

## Ожидаемый результат
Открывается документ

## Фактический результат
![image](https://user-images.githubusercontent.com/60435481/76416635-7e237880-63ac-11ea-9ca9-e3efa7f029bf.png)

**Comment by Dolidenok** [comment]
Неправильная ссылка, там сверху ДЗ где файл readme там папка есть assets, в ней файл нужный.

https://github.com/netology-code/javaqa-homeworks/blob/master/ci/assets/checkstyle.xml
